[build]
  # Comando para fazer o build
  command = "npm run build"
  
  # Diretório que será publicado
  publish = "dist"
  
  # Versão do Node.js
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Configurações de ambiente para o build
  NODE_ENV = "production"

# Configurações de redirecionamento para Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para CSS e JS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 